services:

  mysql:
    image: mysql:8.0
    container_name: materialgrid-mysql

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - materialgrid-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: materialgrid-backend

    restart: unless-stopped

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"

    networks:
      - materialgrid-network

networks:
  materialgrid-network:

volumes:
  mysql_data: