//package com.pixelMind.materialGrid.controller;
//
//import com.pixelMind.materialGrid.dto.request.LicenseCreateRequest;
//import com.pixelMind.materialGrid.dto.request.LicenseUpdateRequest;
//import com.pixelMind.materialGrid.dto.response.ApiResponse;
//import com.pixelMind.materialGrid.dto.response.LicenseResponse;
//import com.pixelMind.materialGrid.dto.response.PageResponse;
//import com.pixelMind.materialGrid.service.LicenseService;
//import io.swagger.v3.oas.annotations.Operation;
//import io.swagger.v3.oas.annotations.tags.Tag;
//import jakarta.validation.Valid;
//import lombok.RequiredArgsConstructor;
//import org.springframework.data.domain.Pageable;
//import org.springframework.data.web.PageableDefault;
//import org.springframework.http.HttpStatus;
//import org.springframework.http.ResponseEntity;
//import org.springframework.web.bind.annotation.*;
//
//@Tag(name = "Licenses", description = "License management with server-generated license codes")
//@RestController
//@RequestMapping("/api/v1/licenses")
//@RequiredArgsConstructor
//public class LicenseController {
//
//    private final LicenseService licenseService;
//
//    @Operation(summary = "Create a license. licenseCode is generated by the server.")
//    @PostMapping
//    public ResponseEntity<ApiResponse<LicenseResponse>> create(@Valid @RequestBody LicenseCreateRequest request) {
//        return ResponseEntity.status(HttpStatus.CREATED)
//                .body(ApiResponse.success("License created successfully", licenseService.createLicense(request)));
//    }
//
//    @Operation(summary = "List licenses (paginated, sortable)")
//    @GetMapping
//    public ResponseEntity<ApiResponse<PageResponse<LicenseResponse>>> getAll(
//            @PageableDefault(size = 20, sort = "id") Pageable pageable) {
//        PageResponse<LicenseResponse> page = new PageResponse<>(licenseService.getLicenses(pageable));
//        return ResponseEntity.ok(ApiResponse.success("Licenses retrieved successfully", page));
//    }
//
//    @Operation(summary = "Get a license by id")
//    @GetMapping("/{id}")
//    public ResponseEntity<ApiResponse<LicenseResponse>> getOne(@PathVariable Long id) {
//        return ResponseEntity.ok(ApiResponse.success("License retrieved successfully", licenseService.getLicense(id)));
//    }
//
//    @Operation(summary = "Update a license (licenseCode is immutable)")
//    @PutMapping("/{id}")
//    public ResponseEntity<ApiResponse<LicenseResponse>> update(
//            @PathVariable Long id, @Valid @RequestBody LicenseUpdateRequest request) {
//        return ResponseEntity.ok(ApiResponse.success("License updated successfully", licenseService.updateLicense(id, request)));
//    }
//
//    @Operation(summary = "Delete a license (blocked if vehicle assignment records exist)")
//    @DeleteMapping("/{id}")
//    public ResponseEntity<ApiResponse<Void>> delete(@PathVariable Long id) {
//        licenseService.deleteLicense(id);
//        return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
//    }
//}
