package com.pixelMind.materialGrid.controller;

import com.pixelMind.materialGrid.dto.request.RouteCreateRequest;
import com.pixelMind.materialGrid.dto.request.RouteUpdateRequest;
import com.pixelMind.materialGrid.dto.response.ApiResponse;
import com.pixelMind.materialGrid.dto.response.PageResponse;
import com.pixelMind.materialGrid.dto.response.RouteResponse;
import com.pixelMind.materialGrid.service.RouteService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@Tag(name = "Routes", description = "Route management with server-generated route codes")
@RestController
@Slf4j
@RequestMapping("/api/v1/routes")
@RequiredArgsConstructor
public class RouteController {

    private final RouteService routeService;

    @Operation(summary = "Create a route. routeCode is generated by the server.")
    @PostMapping
    public ResponseEntity<ApiResponse<RouteResponse>> create(@Valid @RequestBody RouteCreateRequest request) {
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(ApiResponse.success("Route created successfully", routeService.createRoute(request)));
    }

    @Operation(summary = "List routes (paginated, sortable, searchable by start/end location)")
    @GetMapping
    public ResponseEntity<ApiResponse<PageResponse<RouteResponse>>> getAll(
            @RequestParam(required = false) String search,
            @PageableDefault(size = 20, sort = "id") Pageable pageable) {
        PageResponse<RouteResponse> page = new PageResponse<>(routeService.getRoutes(search, pageable));
        return ResponseEntity.ok(ApiResponse.success("Routes retrieved successfully", page));
    }

    @Operation(summary = "Get a route by id")
    @GetMapping("/{id}")
    public ResponseEntity<ApiResponse<RouteResponse>> getOne(@PathVariable Long id) {
        return ResponseEntity.ok(ApiResponse.success("Route retrieved successfully", routeService.getRoute(id)));
    }

    @Operation(summary = "Update a route (routeCode is immutable)")
    @PutMapping("/{id}")
    public ResponseEntity<ApiResponse<RouteResponse>> update(
            @PathVariable Long id, @Valid @RequestBody RouteUpdateRequest request) {
        return ResponseEntity.ok(ApiResponse.success("Route updated successfully", routeService.updateRoute(id, request)));
    }

    @Operation(summary = "Delete a route (blocked if daily route records exist)")
    @DeleteMapping("/{id}")
    public ResponseEntity<ApiResponse<Void>> delete(@PathVariable Long id) {
        routeService.deleteRoute(id);
        return ResponseEntity.ok(ApiResponse.success("Route deleted successfully", null));
    }
}
