spring:
  application:
    name: materialGrid

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2


cors:
  allowed-origins=https://8dd6-111-223-184-150:ngrok-free:app: