-- CREATE TABLE vehicles (
--     id              BIGINT AUTO_INCREMENT PRIMARY KEY,
--     vehicle_number  VARCHAR(20)   NOT NULL,
--     capacity        DECIMAL(10,2) NOT NULL,
--     created_by      VARCHAR(50),
--     created_date    DATETIME(6)   NOT NULL,
--     modified_by     VARCHAR(50),
--     modified_date   DATETIME(6)   NOT NULL,
--     version         BIGINT        NOT NULL DEFAULT 0,
--     active          BOOL        NOT NULL DEFAULT true,
--
--     CONSTRAINT uk_vehicles_vehicle_number UNIQUE (vehicle_number),
--     CONSTRAINT chk_vehicles_capacity_positive CHECK (capacity > 0)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
