-- CREATE TABLE vehicle_licenses (
--     id               BIGINT AUTO_INCREMENT PRIMARY KEY,
--     vehicle_id       BIGINT       NOT NULL,
--     license_id       BIGINT       NOT NULL,
--     assignment_date  DATE         NOT NULL,
--     status           VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
--     created_by       VARCHAR(50),
--     created_date     DATETIME(6)  NOT NULL,
--     modified_by      VARCHAR(50),
--     modified_date    DATETIME(6)  NOT NULL,
--     version          BIGINT       NOT NULL DEFAULT 0,
--
--     -- No UNIQUE(vehicle_id, license_id): a vehicle legitimately holds the
--     -- same license type again after renewal/reissue, each with its own
--     -- date and status. Preventing that would corrupt real business history.
--     -- See VehicleLicenseServiceImpl for the full rationale.
--     CONSTRAINT fk_vehicle_licenses_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id),
--     CONSTRAINT fk_vehicle_licenses_license FOREIGN KEY (license_id) REFERENCES licenses (id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
-- -- Composite index supports the two most common query patterns
-- -- ("licenses for this vehicle", "vehicles for this license") plus status
-- -- filtering without a full table scan.
-- CREATE INDEX idx_vehicle_licenses_vehicle_status ON vehicle_licenses (vehicle_id, status);
-- CREATE INDEX idx_vehicle_licenses_license_status ON vehicle_licenses (license_id, status);
